services:
  mt5:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mt5
    volumes:
      - ./config:/config
    restart: unless-stopped
    ports:
      - 3000:3000
    networks:
      - main_network




networks:
  main_network:
    external: true