services:
  mt5:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: mt5
    shm_size: '2gb'
    environment:
      - VNC_PW=password
    volumes:
      - /home/<path>:/root/.wine/
    ports:
      - 6901:6901
    networks:
      - main_network

networks:
  main_network:
    external: true